### ISSUE TITLE
What license is it under?

### ISSUE THREAD

**Issue by mrkaban** [honghaier-game/TKinterDesigner#30]
Hello, under what license is this software distributed?

**Comment by honghaier-game** [comment]
I added license:
https://github.com/honghaier-game/TKinterDesigner/blob/master/LICENSE

**Comment by mrkaban** [comment]
Thanks for pointing out the license! And thank you for your Python development environment! I added it to a popular Russian-language site about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/tkinterdesigner-graficheskij-interfejs-na-python/)).
